### ISSUE TITLE
Syntax highlighting for dialogue files

### ISSUE THREAD

**Issue by nndda** [nndda/Theatre#1]
References & links:
- Godot documentation:
  - [SyntaxHighlighter](https://docs.godotengine.org/en/stable/classes/class_syntaxhighlighter.html)
  - [ScriptEditor](https://docs.godotengine.org/en/stable/classes/class_scripteditor.html)
  - [ScriptEditorBase](https://docs.godotengine.org/en/stable/classes/class_scripteditorbase.html)
  - [EditorSyntaxHighlighter](https://docs.godotengine.org/en/stable/classes/class_editorsyntaxhighlighter.html)
 
Is this even possible using the built-in text editor? :\

**Comment by JekSun97** [comment]
I just thought about adding this by opening your plugin :)
